# Generated by Django 3.2.4 on 2021-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='No_of_days_present',
            new_name='credits',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='No_of_days_absent',
            new_name='credits_used',
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='credits',
            field=models.CharField(db_column='No_of_days_present', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='credits_used',
            field=models.CharField(db_column='No_of_days_absent', max_length=20),
        ),
    ]
